version: "3.8"
services:
  webapp:
    depends_on:
      - db
    build: .
    ports:
      - "5000:4000"
    environment:
      - NODE_ENV=production
      - DB_URI=mongodb://db:27017/dnd
      - DND_COOKIE_SECRET=${DND_COOKIE_SECRET}
  db:
    image: mongo:4.4.11-rc1
    volumes:
      - ./mongo_volume:/data/db
